import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "EstateMe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
